overblog_graphql:
    definitions:
        schema:
            query: RootQuery
        mappings:
            types:
                - type: attribute
                  dir: "%kernel.project_dir%/src/Common/Infrastructure/Client/Graphql"
                  suffix: ~
                - type: attribute
                  suffix: ~
                  dir: "%kernel.project_dir%/src/Feed/Infrastructure/Client/Graphql"