framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                default_middleware:
                    enabled: true
        transports:
        routing:
