framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                default_middleware:
                    enabled: true
            event.bus:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
        transports:
        routing:
